language: node_js
node_js:
  - "8"
cache:
  directories:
  - "node_modules"

jobs:
  include:
    - stage: Deployment
      deploy:
        provider: heroku
          api_key: $HEROKU_API_KEY
          app: poller-api
          run: "knex migrate:latest --env production"
          on:
            branch: master
    - stage: Test Deployment
      script: 'curl https://poller-api.herokuapp.com'